# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model4.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='model4.proto',
  package='model',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cmodel4.proto\x12\x05model\" \n\x0eGetRoleRequest\x12\x0e\n\x06userID\x18\x01 \x01(\t\"\x1c\n\x0cGetRoleReply\x12\x0c\n\x04role\x18\x01 \x01(\t2F\n\x0bRoleService\x12\x37\n\x07GetRole\x12\x15.model.GetRoleRequest\x1a\x13.model.GetRoleReply\"\x00\x62\x06proto3')
)




_GETROLEREQUEST = _descriptor.Descriptor(
  name='GetRoleRequest',
  full_name='model.GetRoleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userID', full_name='model.GetRoleRequest.userID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=55,
)


_GETROLEREPLY = _descriptor.Descriptor(
  name='GetRoleReply',
  full_name='model.GetRoleReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='role', full_name='model.GetRoleReply.role', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=85,
)

DESCRIPTOR.message_types_by_name['GetRoleRequest'] = _GETROLEREQUEST
DESCRIPTOR.message_types_by_name['GetRoleReply'] = _GETROLEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetRoleRequest = _reflection.GeneratedProtocolMessageType('GetRoleRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETROLEREQUEST,
  __module__ = 'model4_pb2'
  # @@protoc_insertion_point(class_scope:model.GetRoleRequest)
  ))
_sym_db.RegisterMessage(GetRoleRequest)

GetRoleReply = _reflection.GeneratedProtocolMessageType('GetRoleReply', (_message.Message,), dict(
  DESCRIPTOR = _GETROLEREPLY,
  __module__ = 'model4_pb2'
  # @@protoc_insertion_point(class_scope:model.GetRoleReply)
  ))
_sym_db.RegisterMessage(GetRoleReply)



_ROLESERVICE = _descriptor.ServiceDescriptor(
  name='RoleService',
  full_name='model.RoleService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=87,
  serialized_end=157,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetRole',
    full_name='model.RoleService.GetRole',
    index=0,
    containing_service=None,
    input_type=_GETROLEREQUEST,
    output_type=_GETROLEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ROLESERVICE)

DESCRIPTOR.services_by_name['RoleService'] = _ROLESERVICE

# @@protoc_insertion_point(module_scope)
