# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import model4_pb2 as model4__pb2


class RoleServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetRole = channel.unary_unary(
        '/model.RoleService/GetRole',
        request_serializer=model4__pb2.GetRoleRequest.SerializeToString,
        response_deserializer=model4__pb2.GetRoleReply.FromString,
        )


class RoleServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetRole(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RoleServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetRole': grpc.unary_unary_rpc_method_handler(
          servicer.GetRole,
          request_deserializer=model4__pb2.GetRoleRequest.FromString,
          response_serializer=model4__pb2.GetRoleReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'model.RoleService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
